// AUTO-GENERATED BY B.OS TOOLS
const PROJECT_IMAGES_DB = {
    "P01": {
        "images": [
            "img_optimizadas/P01 Estadio BBVA/Aérea_01.jpg",
            "img_optimizadas/P01 Estadio BBVA/Aérea_02.jpg",
            "img_optimizadas/P01 Estadio BBVA/Aérea_03.jpg",
            "img_optimizadas/P01 Estadio BBVA/Cancha_01.jpg",
            "img_optimizadas/P01 Estadio BBVA/Cancha_02.jpg",
            "img_optimizadas/P01 Estadio BBVA/Gradas.jpg",
            "img_optimizadas/P01 Estadio BBVA/Interior.jpg",
            "img_optimizadas/P01 Estadio BBVA/Palco.jpg"
        ]
    },
    "P02": {
        "images": [
            "img_optimizadas/P02 Patrimonio Hoy/Casa_01.jpg",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_02.jpg",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_03.jpg",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_04.jpg",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_05.jpg"
        ]
    },
    "P03": {
        "images": [
            "img_optimizadas/P03 Torre Koi/Aérea_01.jpg",
            "img_optimizadas/P03 Torre Koi/Aérea_02.jpg",
            "img_optimizadas/P03 Torre Koi/Aérea_03.jpg",
            "img_optimizadas/P03 Torre Koi/Aérea_04.jpg",
            "img_optimizadas/P03 Torre Koi/Oficinas_01.jpg",
            "img_optimizadas/P03 Torre Koi/Oficinas_02.jpg",
            "img_optimizadas/P03 Torre Koi/Recámara principal.jpg"
        ]
    },
    "P04": {
        "images": [
            "img_optimizadas/P04 Escuela Secundaria/Acceso principal.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Aérea_01.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Aérea_02.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Calle.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Cancha.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Laboratorio.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Pasillo.jpg",
            "img_optimizadas/P04 Escuela Secundaria/Salón de clases.jpg"
        ]
    },
    "P05": {
        "images": [
            "img_optimizadas/P05 Nave Industrial/Aérea_01.jpg",
            "img_optimizadas/P05 Nave Industrial/Aérea_02.jpg",
            "img_optimizadas/P05 Nave Industrial/Interior_01.jpg",
            "img_optimizadas/P05 Nave Industrial/Interior_02.jpg",
            "img_optimizadas/P05 Nave Industrial/Interior_03.jpg"
        ]
    },
    "P06": {
        "images": [
            "img_optimizadas/P06 Mall/Acceso principal_01.jpg",
            "img_optimizadas/P06 Mall/Acceso principal_02.jpg",
            "img_optimizadas/P06 Mall/Aérea_01.jpg",
            "img_optimizadas/P06 Mall/Aérea_02.jpg",
            "img_optimizadas/P06 Mall/Baño.jpg",
            "img_optimizadas/P06 Mall/Estacionamiento.jpg",
            "img_optimizadas/P06 Mall/Food court_01.jpg",
            "img_optimizadas/P06 Mall/Food court_02.jpg"
        ]
    },
    "P07": {
        "images": [
            "img_optimizadas/P07 Módulo COVID/Acceso principal_01.jpg",
            "img_optimizadas/P07 Módulo COVID/Acceso principal_02.jpg",
            "img_optimizadas/P07 Módulo COVID/Aérea.jpg",
            "img_optimizadas/P07 Módulo COVID/Azotea.jpg",
            "img_optimizadas/P07 Módulo COVID/Baños.jpg",
            "img_optimizadas/P07 Módulo COVID/Interior_01.jpg",
            "img_optimizadas/P07 Módulo COVID/Interior_02.jpg",
            "img_optimizadas/P07 Módulo COVID/Sala de espera.jpg"
        ]
    },
    "P08": {
        "images": [
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Acceso principal.jpg",
            "img_optimizadas/P08 Central de Mezclas/Almacén_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Almacén_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Antibióticos_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Antibióticos_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_05.jpg",
            "img_optimizadas/P08 Central de Mezclas/Baño_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Baño_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Citotóxicos_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Citotóxicos_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Cuarto de Eléctrico_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Cuarto de Eléctrico_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Infografía_CMZ.jpg",
            "img_optimizadas/P08 Central de Mezclas/Jardineras_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Jardineras_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Nutrición Parenteral_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Nutrición Parenteral_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Responsable de Servicio_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Responsable de Servicio_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/RPBI_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/RPBI_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Sala de Espera_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Sala de Espera_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Site_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Site_02.jpg",
            "videos_optimizados/P08 Central de Mezclas/Central de Mezclas.mp4",
            "videos_optimizados/P08 Central de Mezclas/Fachada Principal_01.mp4"
        ]
    },
    "P09": {
        "images": [
            "img_optimizadas/P09 San Quintín/Acceso principal.jpg",
            "img_optimizadas/P09 San Quintín/Aérea 01.jpg",
            "img_optimizadas/P09 San Quintín/Aérea_01.jpg",
            "img_optimizadas/P09 San Quintín/Aérea_02.jpg",
            "img_optimizadas/P09 San Quintín/Cuarto eléctrico.jpg",
            "img_optimizadas/P09 San Quintín/Cuarto hidráulico.jpg",
            "img_optimizadas/P09 San Quintín/Laboratorio.jpg",
            "img_optimizadas/P09 San Quintín/Sala de juntas.jpg"
        ]
    },
    "P10": {
        "images": [
            "img_optimizadas/P10 Puentes Libramiento/Aérea_01.jpg",
            "img_optimizadas/P10 Puentes Libramiento/Aérea_02.jpg",
            "img_optimizadas/P10 Puentes Libramiento/Peatonal_01.jpg",
            "img_optimizadas/P10 Puentes Libramiento/Peatonal_02.jpg",
            "img_optimizadas/P10 Puentes Libramiento/Subestructura.jpg"
        ]
    },
    "P11": {
        "images": [
            "img_optimizadas/P11 Salina Cruz/Calle_01.jpg",
            "img_optimizadas/P11 Salina Cruz/Aérea_01.jpg",
            "img_optimizadas/P11 Salina Cruz/Aérea_02.jpg",
            "img_optimizadas/P11 Salina Cruz/Aérea_03.jpg",
            "img_optimizadas/P11 Salina Cruz/Aérea_04.jpg",
            "img_optimizadas/P11 Salina Cruz/Baño.jpg",
            "img_optimizadas/P11 Salina Cruz/Calle_02.jpg",
            "img_optimizadas/P11 Salina Cruz/Canchas.jpg",
            "img_optimizadas/P11 Salina Cruz/Cuarto hidráulico.jpg",
            "img_optimizadas/P11 Salina Cruz/Guardería.jpg",
            "img_optimizadas/P11 Salina Cruz/Jardín.jpg",
            "img_optimizadas/P11 Salina Cruz/Recámara principal.jpg",
            "img_optimizadas/P11 Salina Cruz/Sala-comedor.jpg",
            "img_optimizadas/P11 Salina Cruz/Subestación eléctrica.jpg"
        ]
    },
    "P12": {
        "images": [
            "img_optimizadas/P12 Silos/Aérea_01.jpg",
            "img_optimizadas/P12 Silos/Aérea_02.jpg",
            "img_optimizadas/P12 Silos/Aérea_03.jpg",
            "img_optimizadas/P12 Silos/Aérea_04.jpg",
            "img_optimizadas/P12 Silos/Caseta.jpg"
        ]
    },
    "P13": {
        "images": [
            "img_optimizadas/P13 Aldaba/Azotea.jpg",
            "img_optimizadas/P13 Aldaba/Baño principal.jpg",
            "img_optimizadas/P13 Aldaba/Fachada principal_01.jpg",
            "img_optimizadas/P13 Aldaba/Fachada principal_02.jpg",
            "img_optimizadas/P13 Aldaba/Jardín.jpg",
            "img_optimizadas/P13 Aldaba/Lavandería.jpg",
            "img_optimizadas/P13 Aldaba/Recámara principal.jpg",
            "img_optimizadas/P13 Aldaba/Sala-comedor.jpg"
        ]
    },
    "P14": {
        "images": [
            "img_optimizadas/P14 Barrio W/Acceso principal_01.jpg",
            "img_optimizadas/P14 Barrio W/Acceso principal_02.jpg",
            "img_optimizadas/P14 Barrio W/Aérea_01.jpg",
            "img_optimizadas/P14 Barrio W/Aérea_02.jpg",
            "img_optimizadas/P14 Barrio W/Aérea_03.jpg",
            "img_optimizadas/P14 Barrio W/Alberca_01.jpg",
            "img_optimizadas/P14 Barrio W/Alberca_02.jpg",
            "img_optimizadas/P14 Barrio W/Azotea.jpg",
            "img_optimizadas/P14 Barrio W/Baño.jpg",
            "img_optimizadas/P14 Barrio W/BRW_01.jpg",
            "img_optimizadas/P14 Barrio W/BRW_02.jpg",
            "img_optimizadas/P14 Barrio W/BRW_05.jpg",
            "img_optimizadas/P14 Barrio W/Cuarto eléctrico.jpg",
            "img_optimizadas/P14 Barrio W/Cuarto hidráulico.jpg",
            "img_optimizadas/P14 Barrio W/Estacionamiento.jpg",
            "img_optimizadas/P14 Barrio W/Gimnasio.jpg",
            "img_optimizadas/P14 Barrio W/Jardin.jpg",
            "img_optimizadas/P14 Barrio W/Lavandería.jpg",
            "img_optimizadas/P14 Barrio W/Lobby.jpg",
            "img_optimizadas/P14 Barrio W/Ludoteca.jpg",
            "img_optimizadas/P14 Barrio W/Oficinas.jpg",
            "img_optimizadas/P14 Barrio W/Penthouse_01.jpg",
            "img_optimizadas/P14 Barrio W/Penthouse_02.jpg",
            "img_optimizadas/P14 Barrio W/Penthouse_03.jpg"
        ]
    },
    "P15": {
        "images": [
            "img_optimizadas/P15 Casa Cerro Abanico/Azotea.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Baño.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_01.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_02.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_03.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Gimnasio.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Jardín_01.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Jardín_02.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Lavandería.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Recámara principal.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Sala-comedor_01.jpg",
            "img_optimizadas/P15 Casa Cerro Abanico/Sala-comedor_02.jpg"
        ]
    },
    "P16": {
        "images": [
            "img_optimizadas/P16 Distrito República/Acceso principal_01.jpg",
            "img_optimizadas/P16 Distrito República/Acceso principal_02.jpg",
            "img_optimizadas/P16 Distrito República/Alberca_01.jpg",
            "img_optimizadas/P16 Distrito República/Alberca_02.jpg",
            "img_optimizadas/P16 Distrito República/Alberca_03.jpg",
            "img_optimizadas/P16 Distrito República/Azotea.jpg",
            "img_optimizadas/P16 Distrito República/Cuarto eléctrico.jpg",
            "img_optimizadas/P16 Distrito República/Cuarto hidráulico.jpg",
            "img_optimizadas/P16 Distrito República/Estacionamiento.jpg",
            "img_optimizadas/P16 Distrito República/Gimnasio.jpg",
            "img_optimizadas/P16 Distrito República/Jardín.jpg",
            "img_optimizadas/P16 Distrito República/Lavandería.jpg",
            "img_optimizadas/P16 Distrito República/Lobby.jpg",
            "img_optimizadas/P16 Distrito República/Ludoteca.jpg",
            "img_optimizadas/P16 Distrito República/Oficinas.jpg",
            "img_optimizadas/P16 Distrito República/Peatonal.jpg"
        ]
    },
    "P17": {
        "images": [
            "img_optimizadas/P17 Esplendor II/Acceso principal_01.jpg",
            "img_optimizadas/P17 Esplendor II/Acceso principal_02.jpg",
            "img_optimizadas/P17 Esplendor II/Alberca-jardín.jpg",
            "img_optimizadas/P17 Esplendor II/Azotea.jpg",
            "img_optimizadas/P17 Esplendor II/Baño.jpg",
            "img_optimizadas/P17 Esplendor II/Calle_01.jpg",
            "img_optimizadas/P17 Esplendor II/Calle_02.jpg",
            "img_optimizadas/P17 Esplendor II/Cocina.jpg",
            "img_optimizadas/P17 Esplendor II/Control de Acceso_01.jpg",
            "img_optimizadas/P17 Esplendor II/Control de Acceso_02.jpg",
            "img_optimizadas/P17 Esplendor II/Cuarto eléctrico.jpg",
            "img_optimizadas/P17 Esplendor II/Cuarto hidráulico.jpg",
            "img_optimizadas/P17 Esplendor II/Fachada principal.jpg",
            "img_optimizadas/P17 Esplendor II/Gimnasio.jpg",
            "img_optimizadas/P17 Esplendor II/Guardería.jpg",
            "img_optimizadas/P17 Esplendor II/Jardín.jpg",
            "img_optimizadas/P17 Esplendor II/Lavandería.jpg",
            "img_optimizadas/P17 Esplendor II/Oficina.jpg",
            "img_optimizadas/P17 Esplendor II/Recámara principal.jpg"
        ]
    },
    "P18": {
        "images": [
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_07.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_03.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Área de Trabajo Grupal_01.JPG",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Área de Trabajo Grupal_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Atención al Público_01.JPG",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Atención al Público_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Azotea.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Baño Familiar_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Baño Familiar_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Casa Hidráulica_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Casa Hidráulica_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_03.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Conmutadores_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Conmutadores_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_03.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_04.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto Eléctrico_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto Eléctrico_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto Eléctrico_Azotea_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto Eléctrico_Azotea_012.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Delta_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Delta_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_03.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_04.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_05.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_06.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Infografía_UMF.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Material de Limpieza_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Material de Limpieza_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_02.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_03.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_04.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_05.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_06.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Sala de Espera_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Sala de Espera_02.jpg",
            "videos_optimizados/P18 Unidad de Medicina Familiar/Acceso_01.mp4",
            "videos_optimizados/P18 Unidad de Medicina Familiar/Pasillo_01.mp4",
            "videos_optimizados/P18 Unidad de Medicina Familiar/Unidad de Medicina Familiar.mp4"
        ]
    },
    "P19": {
        "images": [
            "img_optimizadas/P19 Hospital General de Zona/Acceso Principal_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Acceso Principal_02.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Aérea_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Aérea_02.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Almacén.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Ambulancias.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Azotea_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Azotea_02.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Baños.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Biodigestor.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Comedor.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Cuarto Eléctrico.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Cuarto Hidráulico.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Director del Hospital.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Emergencias.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Estacionamiento.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Farmacia.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Guardería.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Habitación_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Habitación_02.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Infografía_HGZ.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Jardín_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Lavandería.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Pediatría.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Quirófano.jpg",
            "img_optimizadas/P19 Hospital General de Zona/R.P.B.I..jpg",
            "img_optimizadas/P19 Hospital General de Zona/Recepción_01.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Rehabilitación.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Sala de Juntas.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Site.jpg",
            "img_optimizadas/P19 Hospital General de Zona/Subestación Eléctrica.jpg",
            "videos_optimizados/P19 Hospital General de Zona/Acceso principal.mp4",
            "videos_optimizados/P19 Hospital General de Zona/Hospital General de Zona.mp4"
        ]
    },
    "P20": {
        "images": [
            "img_optimizadas/P20 Salón Hernández/Baños.jpg",
            "img_optimizadas/P20 Salón Hernández/Cocina.jpg",
            "img_optimizadas/P20 Salón Hernández/Estacionamiento.jpg",
            "img_optimizadas/P20 Salón Hernández/Fachada principal_01.jpg",
            "img_optimizadas/P20 Salón Hernández/Fachada principal_02.jpg",
            "img_optimizadas/P20 Salón Hernández/Fachada principal_03.jpg",
            "img_optimizadas/P20 Salón Hernández/Salón.jpg"
        ]
    },
    "P21": {
        "images": [
            "img_optimizadas/P21 Belgica/Acceso Principal_01.jpg",
            "img_optimizadas/P21 Belgica/Acceso Principal_02.jpg",
            "img_optimizadas/P21 Belgica/Aérea.jpg",
            "img_optimizadas/P21 Belgica/Alberca.jpg",
            "img_optimizadas/P21 Belgica/Azotea.jpg",
            "img_optimizadas/P21 Belgica/Cuarto Eléctrico.jpg",
            "img_optimizadas/P21 Belgica/Cuarto Hidráulico.jpg",
            "img_optimizadas/P21 Belgica/Estacionamiento.jpg",
            "img_optimizadas/P21 Belgica/Gimnasio_01.jpg",
            "img_optimizadas/P21 Belgica/Gimnasio_02.jpg",
            "img_optimizadas/P21 Belgica/Jardín.jpg",
            "img_optimizadas/P21 Belgica/Lavandería.jpg",
            "img_optimizadas/P21 Belgica/Ludoteca.jpg",
            "img_optimizadas/P21 Belgica/Oficinas.jpg",
            "img_optimizadas/P21 Belgica/Recámara_01.jpg",
            "img_optimizadas/P21 Belgica/Sala-Comedor.jpg"
        ]
    },
    "P22": {
        "images": [
            "img_optimizadas/P22 Metrobús Línea 3/Acceso principal.jpg",
            "img_optimizadas/P22 Metrobús Línea 3/Aérea.jpg",
            "img_optimizadas/P22 Metrobús Línea 3/Calle_01.jpg",
            "img_optimizadas/P22 Metrobús Línea 3/Calle_02.jpg",
            "img_optimizadas/P22 Metrobús Línea 3/Interior_01.jpg",
            "img_optimizadas/P22 Metrobús Línea 3/Interior_02.jpg"
        ]
    },
    "P25": {
        "images": [
            "img_optimizadas/P25 Puentes Periféricos/Aérea_02.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Aérea_01.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Aérea_03.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Aérea_04.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Aérea_05.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Ciclovía_01.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Ciclovía_02.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Infografía_PP.jpg",
            "img_optimizadas/P25 Puentes Periféricos/Subestructura.jpg",
            "videos_optimizados/P25 Puentes Periféricos/Puentes Periféricos.mp4",
            "videos_optimizados/P25 Puentes Periféricos/Puentes Periféricos_01.mp4"
        ]
    },
    "P26": {
        "images": [
            "img_optimizadas/P26 Tawra/Aérea_01.jpg",
            "img_optimizadas/P26 Tawra/Aérea_02.jpg",
            "img_optimizadas/P26 Tawra/Alberca techada.jpg",
            "img_optimizadas/P26 Tawra/Baño.jpg",
            "img_optimizadas/P26 Tawra/Cuarto eléctrico.jpg",
            "img_optimizadas/P26 Tawra/Cuarto hidráulico.jpg",
            "img_optimizadas/P26 Tawra/Estacionamiento.jpg",
            "img_optimizadas/P26 Tawra/Lobby.jpg",
            "img_optimizadas/P26 Tawra/Penthouse_01.jpg",
            "img_optimizadas/P26 Tawra/Penthouse_02.jpg",
            "img_optimizadas/P26 Tawra/Penthouse_03.jpg",
            "img_optimizadas/P26 Tawra/Roof top_01.jpg",
            "img_optimizadas/P26 Tawra/Roof top_02.jpg"
        ]
    },
    "P27": {
        "images": [
            "img_optimizadas/P27 Tren Ligero/Estación Escudo de Armas_02.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Aeropuerto_01.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Aeropuerto_02.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Aeropuerto_03.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Escudo de Armas_01.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Heroe de Nacozari_01.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Heroe de Nacozari_02.jpg",
            "img_optimizadas/P27 Tren Ligero/Estación Heroe de Nacozari_03.jpg",
            "img_optimizadas/P27 Tren Ligero/IMG_20241018_141015.jpg",
            "img_optimizadas/P27 Tren Ligero/Infografía_DRT.jpg",
            "img_optimizadas/P27 Tren Ligero/Talleres_01.jpg",
            "img_optimizadas/P27 Tren Ligero/Talleres_02.jpg",
            "img_optimizadas/P27 Tren Ligero/Talleres_03.jpg",
            "videos_optimizados/P27 Tren Ligero/Estación Heroe de Nacozari_01.mp4",
            "videos_optimizados/P27 Tren Ligero/Tren Ligero.mp4"
        ]
    },
    "P29": {
        "images": [
            "img_optimizadas/P29 Akasia/Acceso principal.jpg",
            "img_optimizadas/P29 Akasia/Alberca.jpg",
            "img_optimizadas/P29 Akasia/Azotea.jpg",
            "img_optimizadas/P29 Akasia/Baño.jpg",
            "img_optimizadas/P29 Akasia/Cuarto eléctrico.jpg",
            "img_optimizadas/P29 Akasia/Estacionamiento.jpg",
            "img_optimizadas/P29 Akasia/Food court_01.jpg",
            "img_optimizadas/P29 Akasia/Food court_02.jpg",
            "img_optimizadas/P29 Akasia/Gimnasio.jpg",
            "img_optimizadas/P29 Akasia/Jardín_01.jpg",
            "img_optimizadas/P29 Akasia/Jardín_02.jpg",
            "img_optimizadas/P29 Akasia/Lavandería.jpg",
            "img_optimizadas/P29 Akasia/Peatonal_01.jpg",
            "img_optimizadas/P29 Akasia/Peatonal_02.jpg",
            "img_optimizadas/P29 Akasia/Sala.jpg",
            "img_optimizadas/P29 Akasia/Sala-comedor_01.jpg"
        ]
    },
    "P30": {
        "images": [
            "img_optimizadas/P30 Grazia/Acceso principal_01.jpg",
            "img_optimizadas/P30 Grazia/Acceso principal_02.jpg",
            "img_optimizadas/P30 Grazia/Azotea.jpg",
            "img_optimizadas/P30 Grazia/Baño.jpg",
            "img_optimizadas/P30 Grazia/Calle.jpg",
            "img_optimizadas/P30 Grazia/Cocina-comedor.jpg",
            "img_optimizadas/P30 Grazia/Cowork.jpg",
            "img_optimizadas/P30 Grazia/Cuarto eléctrico.jpg",
            "img_optimizadas/P30 Grazia/Cuarto hidráulico.jpg",
            "img_optimizadas/P30 Grazia/Estacionamiento.jpg",
            "img_optimizadas/P30 Grazia/Gimnasio.jpg",
            "img_optimizadas/P30 Grazia/Jardín.jpg",
            "img_optimizadas/P30 Grazia/Lavandería.jpg",
            "img_optimizadas/P30 Grazia/Ludoteca.jpg",
            "img_optimizadas/P30 Grazia/Recámara principal.jpg",
            "img_optimizadas/P30 Grazia/Recámara.jpg",
            "img_optimizadas/P30 Grazia/Sala.jpg"
        ]
    },
    "P32": {
        "images": [
            "img_optimizadas/P32 Mediterráneo/Acceso principal_01.jpg",
            "img_optimizadas/P32 Mediterráneo/Acceso principal_02.jpg",
            "img_optimizadas/P32 Mediterráneo/Aérea_01.jpg",
            "img_optimizadas/P32 Mediterráneo/Aérea_02.jpg",
            "img_optimizadas/P32 Mediterráneo/Alberca_01.jpg",
            "img_optimizadas/P32 Mediterráneo/Alberca_02.jpg",
            "img_optimizadas/P32 Mediterráneo/Azotea.jpg",
            "img_optimizadas/P32 Mediterráneo/Baño.jpg",
            "img_optimizadas/P32 Mediterráneo/Baños.jpg",
            "img_optimizadas/P32 Mediterráneo/Cuarto eléctrico.jpg",
            "img_optimizadas/P32 Mediterráneo/Cuarto hidráulico.jpg",
            "img_optimizadas/P32 Mediterráneo/Escaleras.jpg",
            "img_optimizadas/P32 Mediterráneo/Estacionamiento.jpg",
            "img_optimizadas/P32 Mediterráneo/Food court.jpg",
            "img_optimizadas/P32 Mediterráneo/Gimnasio.jpg",
            "img_optimizadas/P32 Mediterráneo/Jardín.jpg",
            "img_optimizadas/P32 Mediterráneo/Lavandería.jpg",
            "img_optimizadas/P32 Mediterráneo/Ludoteca.jpg",
            "img_optimizadas/P32 Mediterráneo/Oficinas.jpg",
            "img_optimizadas/P32 Mediterráneo/Recámara principal.jpg",
            "img_optimizadas/P32 Mediterráneo/Sala-comedor.jpg"
        ]
    },
    "P33": {
        "images": [
            "img_optimizadas/P33 Medline/Acceso principal_01.jpg",
            "img_optimizadas/P33 Medline/Acceso principal_02.jpg",
            "img_optimizadas/P33 Medline/Acceso principal_03.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_01.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_02.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_03.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_04.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_05.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_06.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_07.jpg",
            "img_optimizadas/P33 Medline/Patio de Maniobras_08.jpg"
        ]
    },
    "P34": {
        "images": [
            "img_optimizadas/P34 Carretera San Miguel/Tramo 0+200.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+500.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+600_01.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+600_02.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 4+600.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 6+700_01.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 6+700_02.jpg",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 9+500.jpg"
        ]
    },
    "P35": {
        "images": [
            "img_optimizadas/P35 Naomi/Acceso principal_01.jpg",
            "img_optimizadas/P35 Naomi/Acceso principal_02.jpg",
            "img_optimizadas/P35 Naomi/Aérea_01.jpg",
            "img_optimizadas/P35 Naomi/Aérea_02.jpg",
            "img_optimizadas/P35 Naomi/Aérea_03.jpg",
            "img_optimizadas/P35 Naomi/Alberca_01.jpg",
            "img_optimizadas/P35 Naomi/Alberca_02.jpg",
            "img_optimizadas/P35 Naomi/Azotea.jpg",
            "img_optimizadas/P35 Naomi/Baño.jpg",
            "img_optimizadas/P35 Naomi/Bar.jpg",
            "img_optimizadas/P35 Naomi/Cimentación.jpg",
            "img_optimizadas/P35 Naomi/Cowork.jpg",
            "img_optimizadas/P35 Naomi/Cuarto eléctrico.jpg",
            "img_optimizadas/P35 Naomi/Cuarto hidráulico.jpg",
            "img_optimizadas/P35 Naomi/Estacionamiento.jpg",
            "img_optimizadas/P35 Naomi/Gimnasio.jpg",
            "img_optimizadas/P35 Naomi/Jardín.jpg",
            "img_optimizadas/P35 Naomi/Lavandería.jpg",
            "img_optimizadas/P35 Naomi/Lobby.jpg",
            "img_optimizadas/P35 Naomi/Ludoteca.jpg",
            "img_optimizadas/P35 Naomi/Recámara principal.jpg",
            "img_optimizadas/P35 Naomi/Sala-cocina.jpg"
        ]
    },
    "P36": {
        "images": [
            "img_optimizadas/P36 Residencias TEC/Acceso principal.jpg",
            "img_optimizadas/P36 Residencias TEC/Azotea.jpg",
            "img_optimizadas/P36 Residencias TEC/Baño individual.jpg",
            "img_optimizadas/P36 Residencias TEC/Baños.jpg",
            "img_optimizadas/P36 Residencias TEC/Cafetería.jpg",
            "img_optimizadas/P36 Residencias TEC/Calle_01.jpg",
            "img_optimizadas/P36 Residencias TEC/Calle_02.jpg",
            "img_optimizadas/P36 Residencias TEC/Cowork.jpg",
            "img_optimizadas/P36 Residencias TEC/Cuarto eléctrico.jpg",
            "img_optimizadas/P36 Residencias TEC/Cuarto hidráulico.jpg",
            "img_optimizadas/P36 Residencias TEC/Estacionamiento.jpg",
            "img_optimizadas/P36 Residencias TEC/Gimnasio.jpg",
            "img_optimizadas/P36 Residencias TEC/Recámara_01.jpg",
            "img_optimizadas/P36 Residencias TEC/Recámara_02.jpg",
            "img_optimizadas/P36 Residencias TEC/Sala de juegos_01.jpg",
            "img_optimizadas/P36 Residencias TEC/Sala de juegos_02.jpg",
            "img_optimizadas/P36 Residencias TEC/Terraza_01.jpg",
            "img_optimizadas/P36 Residencias TEC/Terraza_02.jpg",
            "videos_optimizados/P36 Residencias TEC/Residencias TEC.mp4"
        ]
    },
    "P38": {
        "images": [
            "img_optimizadas/P38 Makmul/Acceso principal_01.jpg",
            "img_optimizadas/P38 Makmul/Acceso principal_02.jpg",
            "img_optimizadas/P38 Makmul/Aérea_01.jpg",
            "img_optimizadas/P38 Makmul/Aérea_02.jpg",
            "img_optimizadas/P38 Makmul/Aérea_03.jpg",
            "img_optimizadas/P38 Makmul/Aérea_04.jpg",
            "img_optimizadas/P38 Makmul/Alberca_01.jpg",
            "img_optimizadas/P38 Makmul/Alberca_02.jpg",
            "img_optimizadas/P38 Makmul/Baño.jpg",
            "img_optimizadas/P38 Makmul/Cocina-comedor-sala.jpg",
            "img_optimizadas/P38 Makmul/Cocina-sala.jpg",
            "img_optimizadas/P38 Makmul/Cuarto eléctrico.jpg",
            "img_optimizadas/P38 Makmul/Cuarto hidráulico.jpg",
            "img_optimizadas/P38 Makmul/Estacionamiento.jpg",
            "img_optimizadas/P38 Makmul/Gimnasio.jpg",
            "img_optimizadas/P38 Makmul/Guardería.jpg",
            "img_optimizadas/P38 Makmul/Jardín.jpg",
            "img_optimizadas/P38 Makmul/Lavandería.jpg",
            "img_optimizadas/P38 Makmul/Oficinas.jpg",
            "img_optimizadas/P38 Makmul/Recámara principal.jpg",
            "img_optimizadas/P38 Makmul/Recámara.jpg"
        ]
    },
    "P39": {
        "images": [
            "img_optimizadas/P39 Zonna/Acceso principal.jpg",
            "img_optimizadas/P39 Zonna/Aérea_01.jpg",
            "img_optimizadas/P39 Zonna/Aérea_02.jpg",
            "img_optimizadas/P39 Zonna/Cocina-sala.jpg",
            "img_optimizadas/P39 Zonna/Exterior.jpg",
            "img_optimizadas/P39 Zonna/Jardín.jpg",
            "img_optimizadas/P39 Zonna/Lobby.jpg",
            "img_optimizadas/P39 Zonna/Penthouse.jpg",
            "img_optimizadas/P39 Zonna/Playa.jpg",
            "img_optimizadas/P39 Zonna/Sala_01.jpg",
            "img_optimizadas/P39 Zonna/Sala_02.jpg"
        ]
    },
    "P40": {
        "images": [
            "img_optimizadas/P40 Aulas X/Acceso principal_01.jpg",
            "img_optimizadas/P40 Aulas X/Acceso principal_02.jpg",
            "img_optimizadas/P40 Aulas X/Auditorio.jpg",
            "img_optimizadas/P40 Aulas X/Aula.jpg",
            "img_optimizadas/P40 Aulas X/Azotea.jpg",
            "img_optimizadas/P40 Aulas X/Baños.jpg",
            "img_optimizadas/P40 Aulas X/Cafetería.jpg",
            "img_optimizadas/P40 Aulas X/Cuarto eléctrico.jpg",
            "img_optimizadas/P40 Aulas X/Cuarto hidráulico.jpg",
            "img_optimizadas/P40 Aulas X/Exterior.jpg",
            "img_optimizadas/P40 Aulas X/Jardín.jpg",
            "img_optimizadas/P40 Aulas X/Laboratorio.jpg",
            "img_optimizadas/P40 Aulas X/Vista aérea_01.jpg",
            "img_optimizadas/P40 Aulas X/Vista aérea_02.jpg"
        ]
    },
    "P41": {
        "images": [
            "img_optimizadas/P41 Barrio Santa Lucía/Acceso principal.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Alberca_01.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Alberca_02.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Azotea.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Baño.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Bar.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Cowork.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Cuarto eléctrico.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Cuarto hidráulico.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Estacionamiento.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Gimnasio.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Infografía_BSL.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Jardín.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Lavandería.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Lobby.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Ludoteca.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Peatonal.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Sala-comedor_01.jpg",
            "img_optimizadas/P41 Barrio Santa Lucía/Sala-comedor_02.jpg",
            "videos_optimizados/P41 Barrio Santa Lucía/Alberca_01.mp4",
            "videos_optimizados/P41 Barrio Santa Lucía/Barrio Santa Lucía.mp4",
            "videos_optimizados/P41 Barrio Santa Lucía/Lobby_01.mp4",
            "videos_optimizados/P41 Barrio Santa Lucía/Penthouse_01.mp4"
        ]
    }
};
