// AUTO-GENERATED BY B.OS TOOLS
const PROJECT_IMAGES_DB = {
    "P01": {
        "images": [
            "img_optimizadas/P01 Estadio BBVA/A\u00e9rea_01.png",
            "img_optimizadas/P01 Estadio BBVA/A\u00e9rea_02.png",
            "img_optimizadas/P01 Estadio BBVA/A\u00e9rea_03.png",
            "img_optimizadas/P01 Estadio BBVA/Cancha_01.png",
            "img_optimizadas/P01 Estadio BBVA/Cancha_02.png",
            "img_optimizadas/P01 Estadio BBVA/Gradas.png",
            "img_optimizadas/P01 Estadio BBVA/Interior.png",
            "img_optimizadas/P01 Estadio BBVA/Palco.png"
        ]
    },
    "P02": {
        "images": [
            "img_optimizadas/P02 Patrimonio Hoy/Casa_01.png",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_02.png",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_03.png",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_04.png",
            "img_optimizadas/P02 Patrimonio Hoy/Casa_05.png"
        ]
    },
    "P03": {
        "images": [
            "img_optimizadas/P03 Torre Koi/A\u00e9rea_01.png",
            "img_optimizadas/P03 Torre Koi/A\u00e9rea_02.png",
            "img_optimizadas/P03 Torre Koi/A\u00e9rea_03.png",
            "img_optimizadas/P03 Torre Koi/A\u00e9rea_04.png",
            "img_optimizadas/P03 Torre Koi/Oficinas_01.png",
            "img_optimizadas/P03 Torre Koi/Oficinas_02.png",
            "img_optimizadas/P03 Torre Koi/Rec\u00e1mara principal.png"
        ]
    },
    "P04": {
        "images": [
            "img_optimizadas/P04 Escuela Secundaria/Acceso principal.png",
            "img_optimizadas/P04 Escuela Secundaria/A\u00e9rea_01.png",
            "img_optimizadas/P04 Escuela Secundaria/A\u00e9rea_02.png",
            "img_optimizadas/P04 Escuela Secundaria/Calle.png",
            "img_optimizadas/P04 Escuela Secundaria/Cancha.png",
            "img_optimizadas/P04 Escuela Secundaria/Laboratorio.png",
            "img_optimizadas/P04 Escuela Secundaria/Pasillo.png",
            "img_optimizadas/P04 Escuela Secundaria/Sal\u00f3n de clases.png"
        ]
    },
    "P05": {
        "images": [
            "img_optimizadas/P05 Nave Industrial/A\u00e9rea_01.png",
            "img_optimizadas/P05 Nave Industrial/A\u00e9rea_02.png",
            "img_optimizadas/P05 Nave Industrial/Interior_01.png",
            "img_optimizadas/P05 Nave Industrial/Interior_02.png",
            "img_optimizadas/P05 Nave Industrial/Interior_03.png"
        ]
    },
    "P06": {
        "images": [
            "img_optimizadas/P06 Mall/Acceso principal_01.png",
            "img_optimizadas/P06 Mall/Acceso principal_02.png",
            "img_optimizadas/P06 Mall/A\u00e9rea_01.png",
            "img_optimizadas/P06 Mall/A\u00e9rea_02.png",
            "img_optimizadas/P06 Mall/Ba\u00f1o.png",
            "img_optimizadas/P06 Mall/Estacionamiento.png",
            "img_optimizadas/P06 Mall/Food court_01.png",
            "img_optimizadas/P06 Mall/Food court_02.png"
        ]
    },
    "P07": {
        "images": [
            "img_optimizadas/P07 M\u00f3dulo COVID/Acceso principal_01.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Acceso principal_02.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Azotea.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/A\u00e9rea.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Ba\u00f1os.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Interior_01.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Interior_02.png",
            "img_optimizadas/P07 M\u00f3dulo COVID/Sala de espera.png"
        ]
    },
    "P08": {
        "images": [
            "img_optimizadas/P08 Central de Mezclas/Acceso principal.jpg",
            "img_optimizadas/P08 Central de Mezclas/Almac\u00e9n_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Almac\u00e9n_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Antibi\u00f3ticos_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Antibi\u00f3ticos_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Azotea_05.jpg",
            "img_optimizadas/P08 Central de Mezclas/Ba\u00f1o_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Ba\u00f1o_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Citot\u00f3xicos_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Citot\u00f3xicos_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Cuarto de El\u00e9ctrico_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Cuarto de El\u00e9ctrico_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Estacionamiento_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_03.jpg",
            "img_optimizadas/P08 Central de Mezclas/Fachada Principal_04.jpg",
            "img_optimizadas/P08 Central de Mezclas/Jardineras_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Jardineras_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Nutrici\u00f3n Parenteral_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Nutrici\u00f3n Parenteral_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/RPBI_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/RPBI_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Responsable de Servicio_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Responsable de Servicio_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Sala de Espera_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Sala de Espera_02.jpg",
            "img_optimizadas/P08 Central de Mezclas/Site_01.jpg",
            "img_optimizadas/P08 Central de Mezclas/Site_02.jpg",
            "videos_optimizados/P08 Central de Mezclas/Fachada Principal_01.mp4"
        ]
    },
    "P09": {
        "images": [
            "img_optimizadas/P09 San Quint\u00edn/Acceso principal.png",
            "img_optimizadas/P09 San Quint\u00edn/A\u00e9rea 01.png",
            "img_optimizadas/P09 San Quint\u00edn/A\u00e9rea_01.png",
            "img_optimizadas/P09 San Quint\u00edn/A\u00e9rea_02.png",
            "img_optimizadas/P09 San Quint\u00edn/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P09 San Quint\u00edn/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P09 San Quint\u00edn/Laboratorio.png",
            "img_optimizadas/P09 San Quint\u00edn/Sala de juntas.png"
        ]
    },
    "P10": {
        "images": [
            "img_optimizadas/P10 Puentes Libramiento/A\u00e9rea_01.png",
            "img_optimizadas/P10 Puentes Libramiento/A\u00e9rea_02.png",
            "img_optimizadas/P10 Puentes Libramiento/Peatonal_01.png",
            "img_optimizadas/P10 Puentes Libramiento/Peatonal_02.png",
            "img_optimizadas/P10 Puentes Libramiento/Subestructura.png"
        ]
    },
    "P11": {
        "images": [
            "img_optimizadas/P11 Salina Cruz/A\u00e9rea_01.png",
            "img_optimizadas/P11 Salina Cruz/A\u00e9rea_02.png",
            "img_optimizadas/P11 Salina Cruz/A\u00e9rea_03.png",
            "img_optimizadas/P11 Salina Cruz/A\u00e9rea_04.png",
            "img_optimizadas/P11 Salina Cruz/Ba\u00f1o.png",
            "img_optimizadas/P11 Salina Cruz/Calle_01.png",
            "img_optimizadas/P11 Salina Cruz/Calle_02.png",
            "img_optimizadas/P11 Salina Cruz/Canchas.png",
            "img_optimizadas/P11 Salina Cruz/Cuarto hidr\u00e1ukico.png",
            "img_optimizadas/P11 Salina Cruz/Guarder\u00eda.png",
            "img_optimizadas/P11 Salina Cruz/Jard\u00edn.png",
            "img_optimizadas/P11 Salina Cruz/Rec\u00e1mara principal.png",
            "img_optimizadas/P11 Salina Cruz/Sala-comedor.png",
            "img_optimizadas/P11 Salina Cruz/Subestaci\u00f3n el\u00e9ctrica.png"
        ]
    },
    "P12": {
        "images": []
    },
    "P13": {
        "images": [
            "img_optimizadas/P13 Aldaba/Azotea.png",
            "img_optimizadas/P13 Aldaba/Ba\u00f1o principal.png",
            "img_optimizadas/P13 Aldaba/Fachada principal_01.png",
            "img_optimizadas/P13 Aldaba/Fachada principal_02.png",
            "img_optimizadas/P13 Aldaba/Jard\u00edn.png",
            "img_optimizadas/P13 Aldaba/Lavander\u00eda.png",
            "img_optimizadas/P13 Aldaba/Rec\u00e1mara principal.png",
            "img_optimizadas/P13 Aldaba/Sala-comedor.png"
        ]
    },
    "P14": {
        "images": [
            "img_optimizadas/P14 Barrio W/Acceso principal_01.png",
            "img_optimizadas/P14 Barrio W/Acceso principal_02.png",
            "img_optimizadas/P14 Barrio W/Alberca_01.png",
            "img_optimizadas/P14 Barrio W/Alberca_02.png",
            "img_optimizadas/P14 Barrio W/Azotea.png",
            "img_optimizadas/P14 Barrio W/A\u00e9rea_01.png",
            "img_optimizadas/P14 Barrio W/A\u00e9rea_02.png",
            "img_optimizadas/P14 Barrio W/A\u00e9rea_03.png",
            "img_optimizadas/P14 Barrio W/BRW_01.jpg",
            "img_optimizadas/P14 Barrio W/BRW_02.jpg",
            "img_optimizadas/P14 Barrio W/BRW_05.jpg",
            "img_optimizadas/P14 Barrio W/Ba\u00f1o.png",
            "img_optimizadas/P14 Barrio W/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P14 Barrio W/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P14 Barrio W/Estacionamiento.png",
            "img_optimizadas/P14 Barrio W/Gimnasio.png",
            "img_optimizadas/P14 Barrio W/Jardin.png",
            "img_optimizadas/P14 Barrio W/Lavander\u00eda.png",
            "img_optimizadas/P14 Barrio W/Lobby.png",
            "img_optimizadas/P14 Barrio W/Ludoteca.png",
            "img_optimizadas/P14 Barrio W/Oficinas.png",
            "img_optimizadas/P14 Barrio W/Penthouse_01.png",
            "img_optimizadas/P14 Barrio W/Penthouse_02.png",
            "img_optimizadas/P14 Barrio W/Penthouse_03.png"
        ]
    },
    "P15": {
        "images": [
            "img_optimizadas/P15 Casa Cerro Abanico/Azotea.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Ba\u00f1o.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_01.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_02.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Fachada principal_03.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Gimnasio.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Jard\u00edn_01.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Jard\u00edn_02.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Lavander\u00eda.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Rec\u00e1mara principal.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Sala-comedor_01.png",
            "img_optimizadas/P15 Casa Cerro Abanico/Sala-comedor_02.png"
        ]
    },
    "P16": {
        "images": [
            "img_optimizadas/P16 Distrito Rep\u00fablica/Acceso principal_01.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Acceso principal_02.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Alberca_01.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Alberca_02.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Alberca_03.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Azotea.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Estacionamiento.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Gimnasio.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Jard\u00edn.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Lavander\u00eda.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Lobby.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Ludoteca.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Oficinas.png",
            "img_optimizadas/P16 Distrito Rep\u00fablica/Peatonal.png"
        ]
    },
    "P17": {
        "images": [
            "img_optimizadas/P17 Esplendor II/Acceso principal_01.png",
            "img_optimizadas/P17 Esplendor II/Acceso principal_02.png",
            "img_optimizadas/P17 Esplendor II/Alberca-jard\u00edn.png",
            "img_optimizadas/P17 Esplendor II/Azotea.png",
            "img_optimizadas/P17 Esplendor II/Ba\u00f1o.png",
            "img_optimizadas/P17 Esplendor II/Calle_01.png",
            "img_optimizadas/P17 Esplendor II/Calle_02.png",
            "img_optimizadas/P17 Esplendor II/Cocina.png",
            "img_optimizadas/P17 Esplendor II/Contro de Acceso_01.png",
            "img_optimizadas/P17 Esplendor II/Contro de Acceso_02.png",
            "img_optimizadas/P17 Esplendor II/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P17 Esplendor II/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P17 Esplendor II/Fachada principal.png",
            "img_optimizadas/P17 Esplendor II/Gimnasio.png",
            "img_optimizadas/P17 Esplendor II/Guarder\u00eda.png",
            "img_optimizadas/P17 Esplendor II/Jard\u00edn.png",
            "img_optimizadas/P17 Esplendor II/Lavander\u00eda.png",
            "img_optimizadas/P17 Esplendor II/Oficina.png",
            "img_optimizadas/P17 Esplendor II/Rec\u00e1mara principal.png"
        ]
    },
    "P18": {
        "images": [
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Acceso_03.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Area de Trabajo Grupal_01.JPG",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Area de Trabajo Grupal_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Atenci\u00f3n al Publico_01.JPG",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Atenci\u00f3n al Publico_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Azotea.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Ba\u00f1o Familiar_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Ba\u00f1o Familiar_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Casa Hidr\u00e1ulica_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Casa Hidr\u00e1ulica_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_01.jpg",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Comedor_03.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Conmutadores_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Conmutadores_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_03.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Consultorios_04.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto El\u00e9ctrico_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto El\u00e9ctrico_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto El\u00e9ctrico_Azotea_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Cuarto El\u00e9ctrico_Azotea_012.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Delta_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Delta_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_03.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_04.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_05.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_06.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Exterior_07.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Material de Limpieza_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Material de Limpieza_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_02.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_03.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_04.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_05.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Pasillo_06.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Sala de Espera_01.png",
            "img_optimizadas/P18 Unidad de Medicina Familiar/Sala de Espera_02.png",
            "videos_optimizados/P18 Unidad de Medicina Familiar/Acceso_01.mp4",
            "videos_optimizados/P18 Unidad de Medicina Familiar/Pasillo_01.mp4"
        ]
    },
    "P19": {
        "images": [
            "img_optimizadas/P19 Hospital General de Zona/Acceso Principal_01.png",
            "img_optimizadas/P19 Hospital General de Zona/Acceso Principal_02.png",
            "img_optimizadas/P19 Hospital General de Zona/Almac\u00e9n.png",
            "img_optimizadas/P19 Hospital General de Zona/Ambulancias.png",
            "img_optimizadas/P19 Hospital General de Zona/Azotea_01.png",
            "img_optimizadas/P19 Hospital General de Zona/Azotea_02.png",
            "img_optimizadas/P19 Hospital General de Zona/A\u00e9rea_01.png",
            "img_optimizadas/P19 Hospital General de Zona/A\u00e9rea_02.png",
            "img_optimizadas/P19 Hospital General de Zona/Ba\u00f1os.png",
            "img_optimizadas/P19 Hospital General de Zona/Biodigestor.png",
            "img_optimizadas/P19 Hospital General de Zona/Comedor.png",
            "img_optimizadas/P19 Hospital General de Zona/Cuarto El\u00e9ctrico.png",
            "img_optimizadas/P19 Hospital General de Zona/Cuarto Hidr\u00e1ulico.png",
            "img_optimizadas/P19 Hospital General de Zona/Director del Hospital.png",
            "img_optimizadas/P19 Hospital General de Zona/Emergencias.png",
            "img_optimizadas/P19 Hospital General de Zona/Estacionamiento.png",
            "img_optimizadas/P19 Hospital General de Zona/Farmacia.png",
            "img_optimizadas/P19 Hospital General de Zona/Guarder\u00eda.png",
            "img_optimizadas/P19 Hospital General de Zona/Habitaci\u00f3n_01.png",
            "img_optimizadas/P19 Hospital General de Zona/Habitaci\u00f3n_02.png",
            "img_optimizadas/P19 Hospital General de Zona/Jard\u00edn_01.png",
            "img_optimizadas/P19 Hospital General de Zona/Lavander\u00eda.png",
            "img_optimizadas/P19 Hospital General de Zona/Pediatr\u00eda.png",
            "img_optimizadas/P19 Hospital General de Zona/Quir\u00f3fano.png",
            "img_optimizadas/P19 Hospital General de Zona/R.P.B.I..png",
            "img_optimizadas/P19 Hospital General de Zona/Recepci\u00f3n_01.png",
            "img_optimizadas/P19 Hospital General de Zona/Rehabilitaci\u00f3n.png",
            "img_optimizadas/P19 Hospital General de Zona/Sala de Juntas.png",
            "img_optimizadas/P19 Hospital General de Zona/Site.png",
            "img_optimizadas/P19 Hospital General de Zona/Subestaci\u00f3n El\u00e9ctrica.png",
            "videos_optimizados/P19 Hospital General de Zona/Acceso principal.mp4"
        ]
    },
    "P20": {
        "images": [
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Ba\u00f1os.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Cocina.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Estacionamiento.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Fachada principal_01.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Fachada principal_02.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Fachada principal_03.png",
            "img_optimizadas/P20 Sal\u00f3n Hern\u00e1ndez/Sal\u00f3n.png"
        ]
    },
    "P21": {
        "images": [
            "img_optimizadas/P21 Belgica/Acceso Principal_01.png",
            "img_optimizadas/P21 Belgica/Acceso Principal_02.png",
            "img_optimizadas/P21 Belgica/Alberca.png",
            "img_optimizadas/P21 Belgica/Azotea.png",
            "img_optimizadas/P21 Belgica/A\u00e9rea.png",
            "img_optimizadas/P21 Belgica/Cuarto El\u00e9ctrico.png",
            "img_optimizadas/P21 Belgica/Cuarto Hidr\u00e1ulico.png",
            "img_optimizadas/P21 Belgica/Estacionamiento.png",
            "img_optimizadas/P21 Belgica/Gimnasio_01.png",
            "img_optimizadas/P21 Belgica/Gimnasio_02.png",
            "img_optimizadas/P21 Belgica/Jard\u00edn.png",
            "img_optimizadas/P21 Belgica/Lavander\u00eda.png",
            "img_optimizadas/P21 Belgica/Ludoteca.png",
            "img_optimizadas/P21 Belgica/Oficinas.png",
            "img_optimizadas/P21 Belgica/Rec\u00e1mara_01.png",
            "img_optimizadas/P21 Belgica/Sala-Comedor.png"
        ]
    },
    "P22": {
        "images": [
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/Acceso principal.png",
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/A\u00e9rea.png",
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/Calle_01.png",
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/Calle_02.png",
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/Interior_01.png",
            "img_optimizadas/P22 Metrob\u00fas L\u00ednea 3/Interior_02.png"
        ]
    },
    "P25": {
        "images": [
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/A\u00e9rea_01.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/A\u00e9rea_02.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/A\u00e9rea_03.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/A\u00e9rea_04.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/A\u00e9rea_05.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/Ciclov\u00eda_01.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/Ciclov\u00eda_02.png",
            "img_optimizadas/P25 Puentes Perif\u00e9ricos/Subestructura.png",
            "videos_optimizados/P25 Puentes Perif\u00e9ricos/Puentes Perif\u00e9ricos_01.mp4"
        ]
    },
    "P26": {
        "images": [
            "img_optimizadas/P26 Tawra/Alberca techada.png",
            "img_optimizadas/P26 Tawra/A\u00e9rea_01.png",
            "img_optimizadas/P26 Tawra/A\u00e9rea_02.png",
            "img_optimizadas/P26 Tawra/Ba\u00f1o.png",
            "img_optimizadas/P26 Tawra/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P26 Tawra/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P26 Tawra/Estacionamiento.png",
            "img_optimizadas/P26 Tawra/Lobby.png",
            "img_optimizadas/P26 Tawra/Penthouse_01.png",
            "img_optimizadas/P26 Tawra/Penthouse_02.png",
            "img_optimizadas/P26 Tawra/Penthouse_03.png",
            "img_optimizadas/P26 Tawra/Roof top_01.png",
            "img_optimizadas/P26 Tawra/Roof top_02.png"
        ]
    },
    "P27": {
        "images": [
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Aeropuerto_01.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Aeropuerto_02.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Aeropuerto_03.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Escudo de Armas_01.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Escudo de Armas_02.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Heroe de Nacozari_01.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Heroe de Nacozari_02.png",
            "img_optimizadas/P27 Tren Ligero/Estaci\u00f3n Heroe de Nacozari_03.png",
            "img_optimizadas/P27 Tren Ligero/IMG_20241018_141015.jpg",
            "img_optimizadas/P27 Tren Ligero/Talleres_01.png",
            "img_optimizadas/P27 Tren Ligero/Talleres_02.png",
            "img_optimizadas/P27 Tren Ligero/Talleres_03.png",
            "videos_optimizados/P27 Tren Ligero/Estaci\u00f3n Heroe de Nacozari_01.mp4"
        ]
    },
    "P29": {
        "images": [
            "img_optimizadas/P29 Akasia/Acceso principal.png",
            "img_optimizadas/P29 Akasia/Alberca.png",
            "img_optimizadas/P29 Akasia/Azotea.png",
            "img_optimizadas/P29 Akasia/Ba\u00f1o.png",
            "img_optimizadas/P29 Akasia/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P29 Akasia/Estacionamiento.png",
            "img_optimizadas/P29 Akasia/Food court_01.png",
            "img_optimizadas/P29 Akasia/Food court_02.png",
            "img_optimizadas/P29 Akasia/Gimnasio.png",
            "img_optimizadas/P29 Akasia/Jard\u00edn_01.png",
            "img_optimizadas/P29 Akasia/Jard\u00edn_02.png",
            "img_optimizadas/P29 Akasia/Lavander\u00eda.png",
            "img_optimizadas/P29 Akasia/Peatonal_01.png",
            "img_optimizadas/P29 Akasia/Peatonal_02.png",
            "img_optimizadas/P29 Akasia/Sala-comedor_01.png",
            "img_optimizadas/P29 Akasia/Sala.png"
        ]
    },
    "P30": {
        "images": [
            "img_optimizadas/P30 Grazia/Acceso principal_01.png",
            "img_optimizadas/P30 Grazia/Acceso principal_02.png",
            "img_optimizadas/P30 Grazia/Azotea.png",
            "img_optimizadas/P30 Grazia/Ba\u00f1o.png",
            "img_optimizadas/P30 Grazia/Calle.png",
            "img_optimizadas/P30 Grazia/Cocina-comedor.png",
            "img_optimizadas/P30 Grazia/Cowork.png",
            "img_optimizadas/P30 Grazia/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P30 Grazia/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P30 Grazia/Estaciomiento.png",
            "img_optimizadas/P30 Grazia/Gimnasio.png",
            "img_optimizadas/P30 Grazia/Jard\u00edn.png",
            "img_optimizadas/P30 Grazia/Lavander\u00eda.png",
            "img_optimizadas/P30 Grazia/Ludoteca.png",
            "img_optimizadas/P30 Grazia/Rec\u00e1mara principal.png",
            "img_optimizadas/P30 Grazia/Rec\u00e1mara.png",
            "img_optimizadas/P30 Grazia/Sala.png"
        ]
    },
    "P32": {
        "images": [
            "img_optimizadas/P32 Mediterr\u00e1neo/Acceso principal_01.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Acceso principal_02.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Alberca_01.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Alberca_02.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Azotea.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/A\u00e9rea_01.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/A\u00e9rea_02.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Ba\u00f1o.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Ba\u00f1os.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Escaleras.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Estacionamiento.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Food court.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Gimnasio.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Jard\u00edn.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Lavander\u00eda.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Ludoteca.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Oficinas.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Rec\u00e1mara principal.png",
            "img_optimizadas/P32 Mediterr\u00e1neo/Sala-comedor.png"
        ]
    },
    "P33": {
        "images": [
            "img_optimizadas/P33 Medline/Acceso principal_01.png",
            "img_optimizadas/P33 Medline/Acceso principal_02.png",
            "img_optimizadas/P33 Medline/Acceso principal_03.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_01.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_02.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_03.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_04.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_05.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_06.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_07.png",
            "img_optimizadas/P33 Medline/Patio de Maniobras_08.png"
        ]
    },
    "P34": {
        "images": [
            "img_optimizadas/P34 Carretera San Miguel/Tramo 0+200.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+500.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+600_01.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 3+600_02.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 4+600.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 6+700_01.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 6+700_02.png",
            "img_optimizadas/P34 Carretera San Miguel/Tramo 9+500.png"
        ]
    },
    "P35": {
        "images": [
            "img_optimizadas/P35 Naomi/Acceso principal_01.png",
            "img_optimizadas/P35 Naomi/Acceso principal_02.png",
            "img_optimizadas/P35 Naomi/Alberca_01.png",
            "img_optimizadas/P35 Naomi/Alberca_02.png",
            "img_optimizadas/P35 Naomi/Azotea.png",
            "img_optimizadas/P35 Naomi/A\u00e9rea_01.png",
            "img_optimizadas/P35 Naomi/A\u00e9rea_02.png",
            "img_optimizadas/P35 Naomi/A\u00e9rea_03.png",
            "img_optimizadas/P35 Naomi/Bar.png",
            "img_optimizadas/P35 Naomi/Ba\u00f1o.png",
            "img_optimizadas/P35 Naomi/Cimentaci\u00f3n.png",
            "img_optimizadas/P35 Naomi/Cowork.png",
            "img_optimizadas/P35 Naomi/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P35 Naomi/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P35 Naomi/Estacionamiento.png",
            "img_optimizadas/P35 Naomi/Gimnasio.png",
            "img_optimizadas/P35 Naomi/Jard\u00edn.png",
            "img_optimizadas/P35 Naomi/Lavander\u00eda.png",
            "img_optimizadas/P35 Naomi/Lobby.png",
            "img_optimizadas/P35 Naomi/Ludoteca.png",
            "img_optimizadas/P35 Naomi/Rec\u00e1mara principal.png",
            "img_optimizadas/P35 Naomi/Sala-cocina.png"
        ]
    },
    "P36": {
        "images": [
            "img_optimizadas/P36 Residencias TEC/Acceso principal.png",
            "img_optimizadas/P36 Residencias TEC/Azotea.png",
            "img_optimizadas/P36 Residencias TEC/Ba\u00f1o individual.png",
            "img_optimizadas/P36 Residencias TEC/Ba\u00f1os.png",
            "img_optimizadas/P36 Residencias TEC/Cafeter\u00eda.png",
            "img_optimizadas/P36 Residencias TEC/Calle_01.png",
            "img_optimizadas/P36 Residencias TEC/Calle_02.png",
            "img_optimizadas/P36 Residencias TEC/Cowork.png",
            "img_optimizadas/P36 Residencias TEC/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P36 Residencias TEC/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P36 Residencias TEC/Estacionamiento.png",
            "img_optimizadas/P36 Residencias TEC/Gimnasio.png",
            "img_optimizadas/P36 Residencias TEC/Rec\u00e1mara_01.png",
            "img_optimizadas/P36 Residencias TEC/Rec\u00e1mara_02.png",
            "img_optimizadas/P36 Residencias TEC/Sala de juegos_01.png",
            "img_optimizadas/P36 Residencias TEC/Sala de juegos_02.png",
            "img_optimizadas/P36 Residencias TEC/Terraza_01.png",
            "img_optimizadas/P36 Residencias TEC/Terraza_02.png"
        ]
    },
    "P38": {
        "images": [
            "img_optimizadas/P38 Makmul/Acceso principal_01.png",
            "img_optimizadas/P38 Makmul/Acceso principal_02.png",
            "img_optimizadas/P38 Makmul/Alberca_01.png",
            "img_optimizadas/P38 Makmul/Alberca_02.png",
            "img_optimizadas/P38 Makmul/A\u00e9rea_01.png",
            "img_optimizadas/P38 Makmul/A\u00e9rea_02.png",
            "img_optimizadas/P38 Makmul/A\u00e9rea_03.png",
            "img_optimizadas/P38 Makmul/A\u00e9rea_04.png",
            "img_optimizadas/P38 Makmul/Ba\u00f1o.png",
            "img_optimizadas/P38 Makmul/Cocina-comedor-sala.png",
            "img_optimizadas/P38 Makmul/Cocina-sala.png",
            "img_optimizadas/P38 Makmul/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P38 Makmul/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P38 Makmul/Estacionamiento.png",
            "img_optimizadas/P38 Makmul/Gimnasio.png",
            "img_optimizadas/P38 Makmul/Guarder\u00eda.png",
            "img_optimizadas/P38 Makmul/Jard\u00edn.png",
            "img_optimizadas/P38 Makmul/Lavander\u00eda.png",
            "img_optimizadas/P38 Makmul/Oficinas.png",
            "img_optimizadas/P38 Makmul/Rec\u00e1mara principal.png",
            "img_optimizadas/P38 Makmul/Rec\u00e1mara.png"
        ]
    },
    "P39": {
        "images": [
            "img_optimizadas/P39 Zonna/Acceso principal.png",
            "img_optimizadas/P39 Zonna/A\u00e9rea_01.png",
            "img_optimizadas/P39 Zonna/A\u00e9rea_02.png",
            "img_optimizadas/P39 Zonna/Cocina-sala.png",
            "img_optimizadas/P39 Zonna/Exterior.png",
            "img_optimizadas/P39 Zonna/Jard\u00edn.png",
            "img_optimizadas/P39 Zonna/Lobby.png",
            "img_optimizadas/P39 Zonna/Pentouse.png",
            "img_optimizadas/P39 Zonna/Playa.png",
            "img_optimizadas/P39 Zonna/Sala_01.png",
            "img_optimizadas/P39 Zonna/Sala_02.png"
        ]
    },
    "P40": {
        "images": [
            "img_optimizadas/P40 Aulas X/Acceso principal_01.png",
            "img_optimizadas/P40 Aulas X/Acceso principal_02.png",
            "img_optimizadas/P40 Aulas X/Auditorio.png",
            "img_optimizadas/P40 Aulas X/Aula.png",
            "img_optimizadas/P40 Aulas X/Azotea.png",
            "img_optimizadas/P40 Aulas X/Ba\u00f1os.png",
            "img_optimizadas/P40 Aulas X/Cafeter\u00eda.png",
            "img_optimizadas/P40 Aulas X/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P40 Aulas X/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P40 Aulas X/Exterior.png",
            "img_optimizadas/P40 Aulas X/Jard\u00edn.png",
            "img_optimizadas/P40 Aulas X/Laboratorio.png",
            "img_optimizadas/P40 Aulas X/Vista a\u00e9rea_01.png",
            "img_optimizadas/P40 Aulas X/Vista a\u00e9rea_02.png"
        ]
    },
    "P41": {
        "images": [
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Acceso principal.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Alberca_01.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Alberca_02.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Azotea.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Bar.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Ba\u00f1o.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Cowork.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Cuarto el\u00e9ctrico.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Cuarto hidr\u00e1ulico.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Estacionamiento.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Gimnasio.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Jard\u00edn.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Lavander\u00eda.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Lobby.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Ludoteca.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Peatonal.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Sala-comedor_01.png",
            "img_optimizadas/P41 Barrio Santa Luc\u00eda/Sala-comedor_02.png",
            "videos_optimizados/P41 Barrio Santa Luc\u00eda/Alberca_01.mp4",
            "videos_optimizados/P41 Barrio Santa Luc\u00eda/Lobby_01.mp4",
            "videos_optimizados/P41 Barrio Santa Luc\u00eda/Penthouse_01.mp4"
        ]
    }
};
